apiVersion: v1
kind: Service
metadata:
  name: lab2-frontend-service
spec:
  type: NodePort
  selector:
    app: lab2-frontend
  ports:
    - port: 80        # service port
      targetPort: 3000  # container port
      nodePort: 30081
